{
    "openapi" : "3.0.3",
    "info": {
        "title": "Todolist RESTful API",
        "description": "OpenAPI for Todolist RESTful API",
        "termsOfService": "https://github.com/tomiprasetyo",
        "version": "1",
        "contact": {
            "name": "Tomi Prasetyo",
            "email": "tomi.prasetyo95@gmail.com",
            "url": "https://github.com/tomiprasetyo"
        },
        "license": {
            "name": "APACHE 2.0",
            "url": "https://www.apache.org/licences/LICENCE-2.0"
        }
    },
    "servers": [
        {
            "url": "https://{environment}.akr-bunkerservice.com/api/v1",
            "description": "Todolist RESTful API Server",
            "variables": {
                "environment": {
                    "default": "dev",
                    "description": "Server Environtment",
                    "enum": [
                        "dev",
                        "qa",
                        "prod"
                    ]
                }
            }
        }
    ],
    "externalDocs": {
        "description": "Youtube Programmer Zaman Now",
        "url": "https://www.youtube.com/c/ProgrammerZamanNow"
    },
    "paths": {
        "/todolist": {
            "get": {
                "security": [
                    {
                        "TodolistAuth": []
                    }
                ],
                "tags": ["Todolist"],
                "summary": "Get All Todolist",
                "description": "Only will return active todolist by default",
                "parameters": [
                    {
                        "name": "include done",
                        "required": false,
                        "description": "Is include done todolist",
                        "in": "query",
                        "schema": {
                            "type": "boolean",
                            "nullable": true,
                            "default": false
                        }
                    },
                    {
                        "name": "name",
                        "required": false,
                        "description": "Filter todolist by name",
                        "in": "query",
                        "schema": {
                            "type": "string",
                            "nullable": true,
                            "minLength": 1,
                            "maxLength": 100
                        },
                        "examples": {
                            "java": {
                                "description": "Example name Java",
                                "value": "Java"
                            },
                            "javascript": {
                                "description": "Example name JavaScript",
                                "value": "JavaScript"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success get all todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ArrayTodolist"
                                },
                                "examples": {
                                    "success": {
                                        "description": "Example success get all todolist",
                                        "value": [
                                            {
                                                "id": "1",
                                                "name": "Java",
                                                "priority": 3,
                                                "tags": [
                                                    "Java",
                                                    "Programming"
                                                ]
                                            },
                                            {
                                                "id": "2",
                                                "name": "JavaScript",
                                                "priority": 1,
                                                "tags": [
                                                    "JavaScript", 
                                                    "Programming"
                                                ]
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "TodolistAuth": []
                    }
                ],
                "tags": ["Todolist"],
                "summary": "Create new Todolist",
                "description": "Create new active todolist to database",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateOrUpdateTodolist"
                            },
                            "examples": {
                                "java": {
                                    "description": "Example create Todolist Java",
                                    "value": {
                                        "name": "Java",
                                        "priority": 3,
                                        "tags": [
                                            "Java",
                                            "Programming"
                                        ]
                                    }
                                },
                                "javascript": {
                                    "description": "Example create Todolist JavaScript",
                                    "value": {
                                        "name": "JavaScript",
                                        "priority": 1,
                                        "tags": [
                                            "JavaScript", 
                                            "Programming"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success create todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Todolist"
                                },
                                "examples": {
                                    "java": {
                                        "description": "Success create Java todolist",
                                        "value": {
                                            "id": "1",
                                            "name": "Java",
                                            "priority": 3,
                                            "tags": [
                                                "Java",
                                                "Programming"
                                            ]
                                        }
                                    },
                                    "javascript": {
                                        "description": "Success create JavaScript todolist",
                                        "value": {
                                            "id": "1",
                                            "name": "JavaScript",
                                            "priority": 3,
                                            "tags": [
                                                "JavaScript",
                                                "Programming"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/todolist/{todolistId}": {
            "put": {
                "security": [
                    {
                        "TodolistAuth": []
                    }
                ],
                "tags": ["Todolist"],
                "summary": "Update existing todolist",
                "description": "Update existing todolist in database",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/TodolistId"
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateOrUpdateTodolist"
                            },
                            "examples": {
                                "java": {
                                    "description": "Example update Todolist Java",
                                    "value": {
                                        "name": "Java",
                                        "priority": 3,
                                        "tags": [
                                            "Java", 
                                            "Programming"
                                        ]
                                    }
                                },
                                "javascript": {
                                    "description": "Example update Todolist JavaScript",
                                    "value": {
                                        "name": "JavaScript",
                                        "priority": 1,
                                        "tags": [
                                            "JavaScript", 
                                            "Programming"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success update todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Todolist"
                                },
                                "examples": {
                                    "java": {
                                        "description": "Success update Java todolist",
                                        "value": {
                                            "id": "1",
                                            "name": "Java",
                                            "priority": 3,
                                            "tags": [
                                                "Java",
                                                "Programming"
                                            ]
                                        }
                                    },
                                    "javascript": {
                                        "description": "Success update JavaScript todolist",
                                        "value": {
                                            "id": "1",
                                            "name": "JavaScript",
                                            "priority": 3,
                                            "tags": [
                                                "JavaScript",
                                                "Programming"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "TodolistAuth": []
                    }
                ],
                "tags": ["Todolist"],
                "summary": "Delete existing todolist",
                "description": "Delete existing todolist in database",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/TodolistId"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success delete todolist",
                        "content": {
                         "application/json": {
                             "schema": {
                                 "type": "object",
                                 "properties": {
                                     "success": {
                                         "type": "boolean"
                                    }
                                }
                            },
                            "examples": {
                                "success": {
                                    "description": "Success delete todolist",
                                    "value": {
                                        "success": true
                                    }
                                }
                            }
                        }
                        }
                    },
                    "404": {
                        "description": "Failed delete not found todolist",
                        "content": {
                         "application/json": {
                             "schema": {
                                 "type": "object",
                                 "properties": {
                                     "success": {
                                         "type": "boolean"
                                    }
                                }
                            },
                            "examples": {
                                "failed": {
                                    "description": "Failed delete todolist",
                                    "value": {
                                        "success": false
                                    }
                                }
                            }
                        }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "TodolistAuth": {
                "description": "Authentication for Todolist RESTful API",
                "type": "apiKey",
                "in": "header",
                "name": "X-API-Key"
            }
        },
        "parameters": {
            "TodolistId": {
                "name": "todolistId",
                "in": "path",
                "required": true,
                "description": "Todolist id for updated",
                "schema": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 100
                },
                "examples": {
                    "java": {
                        "description": "Sample todolist id for Java",
                        "value": 1
                    },
                    "javascript": {
                        "description": "Sample todolist id for JavaScript",
                        "value": 2
                    }
                }
            }
        },
        "schemas": {
            "Todolist": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "priority": {
                            "type": "number",
                            "format": "int32"
                        },
                        "tags": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
            },
            "CreateOrUpdateTodolist": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string",
                            "minLength": 1,
                            "required": ["true"]
                        },
                        "priority": {
                            "type": "integer",
                            "format": "int32",
                            "default": 1,
                            "required": ["true"]
                        },
                        "tags": {
                            "type": "array",
                            "required": ["false"],
                            "minItems": 1,
                            "items": {
                                "type": "string",
                                "minLength": 1
                            }
                        }
                }
            },
            "ArrayTodolist": {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/Todolist"
                }
            }
        }
    }
}   